# Generated by Django 5.1 on 2024-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('homepage', models.BooleanField(default=False)),
            ],
        ),
    ]
