# Generated by Django 5.1 on 2024-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_solutions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='image',
            field=models.ImageField(upload_to='solutionss'),
        ),
    ]
